/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'pump' : IDL.Null,
  'pickup' : IDL.Null,
  'tractor' : IDL.Null,
  'trailer' : IDL.Null,
});
export const Time = IDL.Int;
export const AssetLabel = IDL.Variant({
  'tundra' : IDL.Null,
  'threeTank' : IDL.Null,
  'f250' : IDL.Null,
  'f350' : IDL.Null,
  'twoTank' : IDL.Null,
  'notApplicable' : IDL.Null,
  'ptoTractor' : IDL.Null,
  'dodgeRam' : IDL.Null,
});
export const Category = IDL.Variant({
  'killTrucks' : IDL.Null,
  'floatTrailer' : IDL.Null,
  'spareTractors' : IDL.Null,
  'fracPumps' : IDL.Null,
  'misc' : IDL.Null,
  'combo' : IDL.Null,
  'transports' : IDL.Null,
  'acidFracs' : IDL.Null,
  'treatersTrucksAndTrailers' : IDL.Null,
});
export const Asset = IDL.Record({
  'assetLabel' : IDL.Opt(AssetLabel),
  'ownerId' : IDL.Principal,
  'assetNumber' : IDL.Text,
  'vilkDate' : IDL.Opt(Time),
  'standaloneCategory' : IDL.Opt(Category),
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : IDL.Opt(IDL.Text),
});
export const DownAsset = IDL.Record({
  'assetLabel' : IDL.Opt(AssetLabel),
  'ownerId' : IDL.Principal,
  'assetNumber' : IDL.Text,
  'downReason' : IDL.Text,
  'lastUpdated' : IDL.Opt(Time),
  'vilkDate' : IDL.Opt(Time),
  'downDate' : Time,
  'standaloneCategory' : IDL.Opt(Category),
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : IDL.Opt(IDL.Text),
});
export const PairingInfo = IDL.Record({
  'trailerId' : IDL.Text,
  'tractorId' : IDL.Text,
  'notes' : IDL.Text,
  'category' : Category,
  'assetType' : AssetType,
  'driverName' : IDL.Opt(IDL.Text),
});
export const DownAssetWithPairing = IDL.Record({
  'assetLabel' : IDL.Opt(AssetLabel),
  'ownerId' : IDL.Principal,
  'assetNumber' : IDL.Text,
  'downReason' : IDL.Text,
  'lastUpdated' : IDL.Opt(Time),
  'vilkDate' : IDL.Opt(Time),
  'downDate' : Time,
  'standaloneCategory' : IDL.Opt(Category),
  'previousPairing' : IDL.Opt(PairingInfo),
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : IDL.Opt(IDL.Text),
});
export const AssetPairing = IDL.Record({
  'pairedDate' : Time,
  'ownerId' : IDL.Principal,
  'tractorId' : IDL.Text,
  'secondAssetId' : IDL.Text,
  'notes' : IDL.Text,
  'category' : Category,
  'assetType' : AssetType,
  'driverName' : IDL.Opt(IDL.Text),
});
export const AssetHistory = IDL.Record({
  'changeType' : IDL.Variant({
    'created' : IDL.Null,
    'deleted' : IDL.Null,
    'updated' : IDL.Null,
    'paired' : IDL.Null,
    'unpaired' : IDL.Null,
  }),
  'ownerId' : IDL.Principal,
  'assetId' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAsset' : IDL.Func(
      [
        IDL.Text,
        AssetType,
        Time,
        IDL.Opt(Time),
        IDL.Opt(AssetLabel),
        IDL.Opt(Category),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createPairing' : IDL.Func(
      [IDL.Text, IDL.Text, AssetType, Category, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Text], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAllDownAssets' : IDL.Func([], [IDL.Vec(DownAsset)], ['query']),
  'getAllDownAssetsWithPairing' : IDL.Func(
      [],
      [IDL.Vec(DownAssetWithPairing)],
      ['query'],
    ),
  'getAllPairings' : IDL.Func([], [IDL.Vec(AssetPairing)], ['query']),
  'getAssetById' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
  'getAssetHistory' : IDL.Func([], [IDL.Vec(AssetHistory)], ['query']),
  'getAssetsByInspectionStatus' : IDL.Func(
      [IDL.Variant({ 'upcoming' : IDL.Null, 'expired' : IDL.Null })],
      [IDL.Vec(Asset)],
      ['query'],
    ),
  'getAssetsByType' : IDL.Func([AssetType], [IDL.Vec(Asset)], ['query']),
  'getAvailableAssetsForPairing' : IDL.Func(
      [AssetType],
      [IDL.Vec(Asset)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDownAssetById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DownAssetWithPairing)],
      ['query'],
    ),
  'getInspectionAlerts' : IDL.Func(
      [],
      [
        IDL.Record({
          'upcoming' : IDL.Vec(Asset),
          'expired' : IDL.Vec(Asset),
          'upcomingVilk' : IDL.Vec(Asset),
          'expiredVilk' : IDL.Vec(Asset),
        }),
      ],
      ['query'],
    ),
  'getPairingByTractorId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AssetPairing)],
      ['query'],
    ),
  'getPairingsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(AssetPairing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAssetAsDown' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'markAssetAsDownNoPairing' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reactivateDownAsset' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'reactivated' : IDL.Bool, 'restoredPairing' : IDL.Bool })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unpairAssets' : IDL.Func([IDL.Text], [], []),
  'updateAsset' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Opt(Time),
        IDL.Opt(AssetLabel),
        IDL.Opt(Category),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateDownReason' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateDriverName' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updatePairing' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updatePickupDriverName' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'pump' : IDL.Null,
    'pickup' : IDL.Null,
    'tractor' : IDL.Null,
    'trailer' : IDL.Null,
  });
  const Time = IDL.Int;
  const AssetLabel = IDL.Variant({
    'tundra' : IDL.Null,
    'threeTank' : IDL.Null,
    'f250' : IDL.Null,
    'f350' : IDL.Null,
    'twoTank' : IDL.Null,
    'notApplicable' : IDL.Null,
    'ptoTractor' : IDL.Null,
    'dodgeRam' : IDL.Null,
  });
  const Category = IDL.Variant({
    'killTrucks' : IDL.Null,
    'floatTrailer' : IDL.Null,
    'spareTractors' : IDL.Null,
    'fracPumps' : IDL.Null,
    'misc' : IDL.Null,
    'combo' : IDL.Null,
    'transports' : IDL.Null,
    'acidFracs' : IDL.Null,
    'treatersTrucksAndTrailers' : IDL.Null,
  });
  const Asset = IDL.Record({
    'assetLabel' : IDL.Opt(AssetLabel),
    'ownerId' : IDL.Principal,
    'assetNumber' : IDL.Text,
    'vilkDate' : IDL.Opt(Time),
    'standaloneCategory' : IDL.Opt(Category),
    'aviDate' : Time,
    'assetType' : AssetType,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const DownAsset = IDL.Record({
    'assetLabel' : IDL.Opt(AssetLabel),
    'ownerId' : IDL.Principal,
    'assetNumber' : IDL.Text,
    'downReason' : IDL.Text,
    'lastUpdated' : IDL.Opt(Time),
    'vilkDate' : IDL.Opt(Time),
    'downDate' : Time,
    'standaloneCategory' : IDL.Opt(Category),
    'aviDate' : Time,
    'assetType' : AssetType,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const PairingInfo = IDL.Record({
    'trailerId' : IDL.Text,
    'tractorId' : IDL.Text,
    'notes' : IDL.Text,
    'category' : Category,
    'assetType' : AssetType,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const DownAssetWithPairing = IDL.Record({
    'assetLabel' : IDL.Opt(AssetLabel),
    'ownerId' : IDL.Principal,
    'assetNumber' : IDL.Text,
    'downReason' : IDL.Text,
    'lastUpdated' : IDL.Opt(Time),
    'vilkDate' : IDL.Opt(Time),
    'downDate' : Time,
    'standaloneCategory' : IDL.Opt(Category),
    'previousPairing' : IDL.Opt(PairingInfo),
    'aviDate' : Time,
    'assetType' : AssetType,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const AssetPairing = IDL.Record({
    'pairedDate' : Time,
    'ownerId' : IDL.Principal,
    'tractorId' : IDL.Text,
    'secondAssetId' : IDL.Text,
    'notes' : IDL.Text,
    'category' : Category,
    'assetType' : AssetType,
    'driverName' : IDL.Opt(IDL.Text),
  });
  const AssetHistory = IDL.Record({
    'changeType' : IDL.Variant({
      'created' : IDL.Null,
      'deleted' : IDL.Null,
      'updated' : IDL.Null,
      'paired' : IDL.Null,
      'unpaired' : IDL.Null,
    }),
    'ownerId' : IDL.Principal,
    'assetId' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAsset' : IDL.Func(
        [
          IDL.Text,
          AssetType,
          Time,
          IDL.Opt(Time),
          IDL.Opt(AssetLabel),
          IDL.Opt(Category),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createPairing' : IDL.Func(
        [IDL.Text, IDL.Text, AssetType, Category, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Text], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAllDownAssets' : IDL.Func([], [IDL.Vec(DownAsset)], ['query']),
    'getAllDownAssetsWithPairing' : IDL.Func(
        [],
        [IDL.Vec(DownAssetWithPairing)],
        ['query'],
      ),
    'getAllPairings' : IDL.Func([], [IDL.Vec(AssetPairing)], ['query']),
    'getAssetById' : IDL.Func([IDL.Text], [IDL.Opt(Asset)], ['query']),
    'getAssetHistory' : IDL.Func([], [IDL.Vec(AssetHistory)], ['query']),
    'getAssetsByInspectionStatus' : IDL.Func(
        [IDL.Variant({ 'upcoming' : IDL.Null, 'expired' : IDL.Null })],
        [IDL.Vec(Asset)],
        ['query'],
      ),
    'getAssetsByType' : IDL.Func([AssetType], [IDL.Vec(Asset)], ['query']),
    'getAvailableAssetsForPairing' : IDL.Func(
        [AssetType],
        [IDL.Vec(Asset)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDownAssetById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DownAssetWithPairing)],
        ['query'],
      ),
    'getInspectionAlerts' : IDL.Func(
        [],
        [
          IDL.Record({
            'upcoming' : IDL.Vec(Asset),
            'expired' : IDL.Vec(Asset),
            'upcomingVilk' : IDL.Vec(Asset),
            'expiredVilk' : IDL.Vec(Asset),
          }),
        ],
        ['query'],
      ),
    'getPairingByTractorId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AssetPairing)],
        ['query'],
      ),
    'getPairingsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(AssetPairing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAssetAsDown' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'markAssetAsDownNoPairing' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reactivateDownAsset' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'reactivated' : IDL.Bool,
            'restoredPairing' : IDL.Bool,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unpairAssets' : IDL.Func([IDL.Text], [], []),
    'updateAsset' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Opt(Time),
          IDL.Opt(AssetLabel),
          IDL.Opt(Category),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateDownReason' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateDriverName' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'updatePairing' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updatePickupDriverName' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };