/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'assetLabel' : [] | [AssetLabel],
  'ownerId' : Principal,
  'assetNumber' : string,
  'vilkDate' : [] | [Time],
  'standaloneCategory' : [] | [Category],
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : [] | [string],
}
export interface AssetHistory {
  'changeType' : { 'created' : null } |
    { 'deleted' : null } |
    { 'updated' : null } |
    { 'paired' : null } |
    { 'unpaired' : null },
  'ownerId' : Principal,
  'assetId' : string,
  'timestamp' : Time,
  'details' : string,
}
export type AssetLabel = { 'tundra' : null } |
  { 'threeTank' : null } |
  { 'f250' : null } |
  { 'f350' : null } |
  { 'twoTank' : null } |
  { 'notApplicable' : null } |
  { 'ptoTractor' : null } |
  { 'dodgeRam' : null };
export interface AssetPairing {
  'pairedDate' : Time,
  'ownerId' : Principal,
  'tractorId' : string,
  'secondAssetId' : string,
  'notes' : string,
  'category' : Category,
  'assetType' : AssetType,
  'driverName' : [] | [string],
}
export type AssetType = { 'pump' : null } |
  { 'pickup' : null } |
  { 'tractor' : null } |
  { 'trailer' : null };
export type Category = { 'killTrucks' : null } |
  { 'floatTrailer' : null } |
  { 'spareTractors' : null } |
  { 'fracPumps' : null } |
  { 'misc' : null } |
  { 'combo' : null } |
  { 'transports' : null } |
  { 'acidFracs' : null } |
  { 'treatersTrucksAndTrailers' : null };
export interface DownAsset {
  'assetLabel' : [] | [AssetLabel],
  'ownerId' : Principal,
  'assetNumber' : string,
  'downReason' : string,
  'lastUpdated' : [] | [Time],
  'vilkDate' : [] | [Time],
  'downDate' : Time,
  'standaloneCategory' : [] | [Category],
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : [] | [string],
}
export interface DownAssetWithPairing {
  'assetLabel' : [] | [AssetLabel],
  'ownerId' : Principal,
  'assetNumber' : string,
  'downReason' : string,
  'lastUpdated' : [] | [Time],
  'vilkDate' : [] | [Time],
  'downDate' : Time,
  'standaloneCategory' : [] | [Category],
  'previousPairing' : [] | [PairingInfo],
  'aviDate' : Time,
  'assetType' : AssetType,
  'driverName' : [] | [string],
}
export interface PairingInfo {
  'trailerId' : string,
  'tractorId' : string,
  'notes' : string,
  'category' : Category,
  'assetType' : AssetType,
  'driverName' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAsset' : ActorMethod<
    [
      string,
      AssetType,
      Time,
      [] | [Time],
      [] | [AssetLabel],
      [] | [Category],
      [] | [string],
    ],
    undefined
  >,
  'createPairing' : ActorMethod<
    [string, string, AssetType, Category, string, [] | [string]],
    undefined
  >,
  'deleteAsset' : ActorMethod<[string], undefined>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAllDownAssets' : ActorMethod<[], Array<DownAsset>>,
  'getAllDownAssetsWithPairing' : ActorMethod<[], Array<DownAssetWithPairing>>,
  'getAllPairings' : ActorMethod<[], Array<AssetPairing>>,
  'getAssetById' : ActorMethod<[string], [] | [Asset]>,
  'getAssetHistory' : ActorMethod<[], Array<AssetHistory>>,
  'getAssetsByInspectionStatus' : ActorMethod<
    [{ 'upcoming' : null } | { 'expired' : null }],
    Array<Asset>
  >,
  'getAssetsByType' : ActorMethod<[AssetType], Array<Asset>>,
  'getAvailableAssetsForPairing' : ActorMethod<[AssetType], Array<Asset>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDownAssetById' : ActorMethod<[string], [] | [DownAssetWithPairing]>,
  'getInspectionAlerts' : ActorMethod<
    [],
    {
      'upcoming' : Array<Asset>,
      'expired' : Array<Asset>,
      'upcomingVilk' : Array<Asset>,
      'expiredVilk' : Array<Asset>,
    }
  >,
  'getPairingByTractorId' : ActorMethod<[string], [] | [AssetPairing]>,
  'getPairingsByCategory' : ActorMethod<[Category], Array<AssetPairing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAssetAsDown' : ActorMethod<[string, string], undefined>,
  'markAssetAsDownNoPairing' : ActorMethod<[string, string], undefined>,
  'reactivateDownAsset' : ActorMethod<
    [string],
    { 'reactivated' : boolean, 'restoredPairing' : boolean }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unpairAssets' : ActorMethod<[string], undefined>,
  'updateAsset' : ActorMethod<
    [
      string,
      Time,
      [] | [Time],
      [] | [AssetLabel],
      [] | [Category],
      [] | [string],
    ],
    undefined
  >,
  'updateDownReason' : ActorMethod<[string, string], undefined>,
  'updateDriverName' : ActorMethod<[string, [] | [string]], undefined>,
  'updatePairing' : ActorMethod<
    [string, Category, string, [] | [string]],
    undefined
  >,
  'updatePickupDriverName' : ActorMethod<[string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];