/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface PairingInfo {
    trailerId: string;
    tractorId: string;
    notes: string;
    category: Category;
    assetType: AssetType;
    driverName?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DownAssetWithPairing {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated?: Time;
    vilkDate?: Time;
    downDate: Time;
    standaloneCategory?: Category;
    previousPairing?: PairingInfo;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
}
export interface AssetPairing {
    pairedDate: Time;
    ownerId: Principal;
    tractorId: string;
    secondAssetId: string;
    notes: string;
    category: Category;
    assetType: AssetType;
    driverName?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DownAsset {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated?: Time;
    vilkDate?: Time;
    downDate: Time;
    standaloneCategory?: Category;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
}
export interface AssetHistory {
    changeType: Variant_created_deleted_updated_paired_unpaired;
    ownerId: Principal;
    assetId: string;
    timestamp: Time;
    details: string;
}
export interface Asset {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    vilkDate?: Time;
    standaloneCategory?: Category;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
}
export enum AssetLabel {
    tundra = "tundra",
    threeTank = "threeTank",
    f250 = "f250",
    f350 = "f350",
    twoTank = "twoTank",
    notApplicable = "notApplicable",
    ptoTractor = "ptoTractor",
    dodgeRam = "dodgeRam"
}
export enum AssetType {
    pump = "pump",
    pickup = "pickup",
    tractor = "tractor",
    trailer = "trailer"
}
export enum Category {
    killTrucks = "killTrucks",
    floatTrailer = "floatTrailer",
    spareTractors = "spareTractors",
    fracPumps = "fracPumps",
    misc = "misc",
    combo = "combo",
    transports = "transports",
    acidFracs = "acidFracs",
    treatersTrucksAndTrailers = "treatersTrucksAndTrailers"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_created_deleted_updated_paired_unpaired {
    created = "created",
    deleted = "deleted",
    updated = "updated",
    paired = "paired",
    unpaired = "unpaired"
}
export enum Variant_upcoming_expired {
    upcoming = "upcoming",
    expired = "expired"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAsset(assetNumber: string, assetType: AssetType, aviDate: Time, vilkDate: Time | null, assetLabel: AssetLabel | null, standaloneCategory: Category | null, driverName: string | null): Promise<void>;
    createPairing(tractorId: string, secondAssetId: string, assetType: AssetType, category: Category, notes: string, driverName: string | null): Promise<void>;
    deleteAsset(assetNumber: string): Promise<void>;
    getAllAssets(): Promise<Array<Asset>>;
    getAllDownAssets(): Promise<Array<DownAsset>>;
    getAllDownAssetsWithPairing(): Promise<Array<DownAssetWithPairing>>;
    getAllPairings(): Promise<Array<AssetPairing>>;
    getAssetById(assetNumber: string): Promise<Asset | null>;
    getAssetHistory(): Promise<Array<AssetHistory>>;
    getAssetsByInspectionStatus(status: Variant_upcoming_expired): Promise<Array<Asset>>;
    getAssetsByType(assetType: AssetType): Promise<Array<Asset>>;
    getAvailableAssetsForPairing(assetType: AssetType): Promise<Array<Asset>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDownAssetById(assetNumber: string): Promise<DownAssetWithPairing | null>;
    getInspectionAlerts(): Promise<{
        upcoming: Array<Asset>;
        expired: Array<Asset>;
        upcomingVilk: Array<Asset>;
        expiredVilk: Array<Asset>;
    }>;
    getPairingByTractorId(tractorId: string): Promise<AssetPairing | null>;
    getPairingsByCategory(category: Category): Promise<Array<AssetPairing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAssetAsDown(assetNumber: string, reason: string): Promise<void>;
    markAssetAsDownNoPairing(assetNumber: string, reason: string): Promise<void>;
    reactivateDownAsset(assetNumber: string): Promise<{
        reactivated: boolean;
        restoredPairing: boolean;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unpairAssets(tractorId: string): Promise<void>;
    updateAsset(assetNumber: string, newAviDate: Time, newVilkDate: Time | null, newAssetLabel: AssetLabel | null, newStandaloneCategory: Category | null, newDriverName: string | null): Promise<void>;
    updateDownReason(assetNumber: string, newReason: string): Promise<void>;
    updateDriverName(tractorId: string, driverName: string | null): Promise<void>;
    updatePairing(tractorId: string, category: Category, notes: string, driverName: string | null): Promise<void>;
    updatePickupDriverName(assetNumber: string, driverName: string | null): Promise<void>;
}
import type { Asset as _Asset, AssetHistory as _AssetHistory, AssetLabel as _AssetLabel, AssetPairing as _AssetPairing, AssetType as _AssetType, Category as _Category, DownAsset as _DownAsset, DownAssetWithPairing as _DownAssetWithPairing, PairingInfo as _PairingInfo, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAsset(arg0: string, arg1: AssetType, arg2: Time, arg3: Time | null, arg4: AssetLabel | null, arg5: Category | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAsset(arg0, to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAsset(arg0, to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createPairing(arg0: string, arg1: string, arg2: AssetType, arg3: Category, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPairing(arg0, arg1, to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPairing(arg0, arg1, to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteAsset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDownAssets(): Promise<Array<DownAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDownAssets();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDownAssets();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDownAssetsWithPairing(): Promise<Array<DownAssetWithPairing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDownAssetsWithPairing();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDownAssetsWithPairing();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPairings(): Promise<Array<AssetPairing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPairings();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPairings();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetById(arg0: string): Promise<Asset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetById(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetById(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetHistory(): Promise<Array<AssetHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetHistory();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetHistory();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByInspectionStatus(arg0: Variant_upcoming_expired): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByInspectionStatus(to_candid_variant_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByInspectionStatus(to_candid_variant_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetsByType(arg0: AssetType): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByType(to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByType(to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableAssetsForPairing(arg0: AssetType): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableAssetsForPairing(to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableAssetsForPairing(to_candid_AssetType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDownAssetById(arg0: string): Promise<DownAssetWithPairing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownAssetById(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownAssetById(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionAlerts(): Promise<{
        upcoming: Array<Asset>;
        expired: Array<Asset>;
        upcomingVilk: Array<Asset>;
        expiredVilk: Array<Asset>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionAlerts();
                return from_candid_record_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionAlerts();
            return from_candid_record_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairingByTractorId(arg0: string): Promise<AssetPairing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairingByTractorId(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairingByTractorId(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairingsByCategory(arg0: Category): Promise<Array<AssetPairing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairingsByCategory(to_candid_Category_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairingsByCategory(to_candid_Category_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAssetAsDown(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssetAsDown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssetAsDown(arg0, arg1);
            return result;
        }
    }
    async markAssetAsDownNoPairing(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssetAsDownNoPairing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssetAsDownNoPairing(arg0, arg1);
            return result;
        }
    }
    async reactivateDownAsset(arg0: string): Promise<{
        reactivated: boolean;
        restoredPairing: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateDownAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateDownAsset(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unpairAssets(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpairAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpairAssets(arg0);
            return result;
        }
    }
    async updateAsset(arg0: string, arg1: Time, arg2: Time | null, arg3: AssetLabel | null, arg4: Category | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateDownReason(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDownReason(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDownReason(arg0, arg1);
            return result;
        }
    }
    async updateDriverName(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriverName(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriverName(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePairing(arg0: string, arg1: Category, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePairing(arg0, to_candid_Category_n17(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePairing(arg0, to_candid_Category_n17(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updatePickupDriverName(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickupDriverName(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickupDriverName(arg0, to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AssetHistory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetHistory): AssetHistory {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_AssetLabel_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetLabel): AssetLabel {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AssetPairing_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetPairing): AssetPairing {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_AssetType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Asset_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DownAssetWithPairing_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DownAssetWithPairing): DownAssetWithPairing {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_DownAsset_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DownAsset): DownAsset {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PairingInfo_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PairingInfo): PairingInfo {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssetLabel]): AssetLabel | null {
    return value.length === 0 ? null : from_candid_AssetLabel_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PairingInfo]): PairingInfo | null {
    return value.length === 0 ? null : from_candid_PairingInfo_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : from_candid_Asset_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DownAssetWithPairing]): DownAssetWithPairing | null {
    return value.length === 0 ? null : from_candid_DownAssetWithPairing_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssetPairing]): AssetPairing | null {
    return value.length === 0 ? null : from_candid_AssetPairing_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assetLabel: [] | [_AssetLabel];
    ownerId: Principal;
    assetNumber: string;
    vilkDate: [] | [_Time];
    standaloneCategory: [] | [_Category];
    aviDate: _Time;
    assetType: _AssetType;
    driverName: [] | [string];
}): {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    vilkDate?: Time;
    standaloneCategory?: Category;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
} {
    return {
        assetLabel: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assetLabel)),
        ownerId: value.ownerId,
        assetNumber: value.assetNumber,
        vilkDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.vilkDate)),
        standaloneCategory: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.standaloneCategory)),
        aviDate: value.aviDate,
        assetType: from_candid_AssetType_n30(_uploadFile, _downloadFile, value.assetType),
        driverName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assetLabel: [] | [_AssetLabel];
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated: [] | [_Time];
    vilkDate: [] | [_Time];
    downDate: _Time;
    standaloneCategory: [] | [_Category];
    aviDate: _Time;
    assetType: _AssetType;
    driverName: [] | [string];
}): {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated?: Time;
    vilkDate?: Time;
    downDate: Time;
    standaloneCategory?: Category;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
} {
    return {
        assetLabel: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assetLabel)),
        ownerId: value.ownerId,
        assetNumber: value.assetNumber,
        downReason: value.downReason,
        lastUpdated: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastUpdated)),
        vilkDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.vilkDate)),
        downDate: value.downDate,
        standaloneCategory: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.standaloneCategory)),
        aviDate: value.aviDate,
        assetType: from_candid_AssetType_n30(_uploadFile, _downloadFile, value.assetType),
        driverName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assetLabel: [] | [_AssetLabel];
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated: [] | [_Time];
    vilkDate: [] | [_Time];
    downDate: _Time;
    standaloneCategory: [] | [_Category];
    previousPairing: [] | [_PairingInfo];
    aviDate: _Time;
    assetType: _AssetType;
    driverName: [] | [string];
}): {
    assetLabel?: AssetLabel;
    ownerId: Principal;
    assetNumber: string;
    downReason: string;
    lastUpdated?: Time;
    vilkDate?: Time;
    downDate: Time;
    standaloneCategory?: Category;
    previousPairing?: PairingInfo;
    aviDate: Time;
    assetType: AssetType;
    driverName?: string;
} {
    return {
        assetLabel: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.assetLabel)),
        ownerId: value.ownerId,
        assetNumber: value.assetNumber,
        downReason: value.downReason,
        lastUpdated: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastUpdated)),
        vilkDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.vilkDate)),
        downDate: value.downDate,
        standaloneCategory: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.standaloneCategory)),
        previousPairing: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.previousPairing)),
        aviDate: value.aviDate,
        assetType: from_candid_AssetType_n30(_uploadFile, _downloadFile, value.assetType),
        driverName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trailerId: string;
    tractorId: string;
    notes: string;
    category: _Category;
    assetType: _AssetType;
    driverName: [] | [string];
}): {
    trailerId: string;
    tractorId: string;
    notes: string;
    category: Category;
    assetType: AssetType;
    driverName?: string;
} {
    return {
        trailerId: value.trailerId,
        tractorId: value.tractorId,
        notes: value.notes,
        category: from_candid_Category_n28(_uploadFile, _downloadFile, value.category),
        assetType: from_candid_AssetType_n30(_uploadFile, _downloadFile, value.assetType),
        driverName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pairedDate: _Time;
    ownerId: Principal;
    tractorId: string;
    secondAssetId: string;
    notes: string;
    category: _Category;
    assetType: _AssetType;
    driverName: [] | [string];
}): {
    pairedDate: Time;
    ownerId: Principal;
    tractorId: string;
    secondAssetId: string;
    notes: string;
    category: Category;
    assetType: AssetType;
    driverName?: string;
} {
    return {
        pairedDate: value.pairedDate,
        ownerId: value.ownerId,
        tractorId: value.tractorId,
        secondAssetId: value.secondAssetId,
        notes: value.notes,
        category: from_candid_Category_n28(_uploadFile, _downloadFile, value.category),
        assetType: from_candid_AssetType_n30(_uploadFile, _downloadFile, value.assetType),
        driverName: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    changeType: {
        created: null;
    } | {
        deleted: null;
    } | {
        updated: null;
    } | {
        paired: null;
    } | {
        unpaired: null;
    };
    ownerId: Principal;
    assetId: string;
    timestamp: _Time;
    details: string;
}): {
    changeType: Variant_created_deleted_updated_paired_unpaired;
    ownerId: Principal;
    assetId: string;
    timestamp: Time;
    details: string;
} {
    return {
        changeType: from_candid_variant_n49(_uploadFile, _downloadFile, value.changeType),
        ownerId: value.ownerId,
        assetId: value.assetId,
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: Array<_Asset>;
    expired: Array<_Asset>;
    upcomingVilk: Array<_Asset>;
    expiredVilk: Array<_Asset>;
}): {
    upcoming: Array<Asset>;
    expired: Array<Asset>;
    upcomingVilk: Array<Asset>;
    expiredVilk: Array<Asset>;
} {
    return {
        upcoming: from_candid_vec_n20(_uploadFile, _downloadFile, value.upcoming),
        expired: from_candid_vec_n20(_uploadFile, _downloadFile, value.expired),
        upcomingVilk: from_candid_vec_n20(_uploadFile, _downloadFile, value.upcomingVilk),
        expiredVilk: from_candid_vec_n20(_uploadFile, _downloadFile, value.expiredVilk)
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tundra: null;
} | {
    threeTank: null;
} | {
    f250: null;
} | {
    f350: null;
} | {
    twoTank: null;
} | {
    notApplicable: null;
} | {
    ptoTractor: null;
} | {
    dodgeRam: null;
}): AssetLabel {
    return "tundra" in value ? AssetLabel.tundra : "threeTank" in value ? AssetLabel.threeTank : "f250" in value ? AssetLabel.f250 : "f350" in value ? AssetLabel.f350 : "twoTank" in value ? AssetLabel.twoTank : "notApplicable" in value ? AssetLabel.notApplicable : "ptoTractor" in value ? AssetLabel.ptoTractor : "dodgeRam" in value ? AssetLabel.dodgeRam : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    killTrucks: null;
} | {
    floatTrailer: null;
} | {
    spareTractors: null;
} | {
    fracPumps: null;
} | {
    misc: null;
} | {
    combo: null;
} | {
    transports: null;
} | {
    acidFracs: null;
} | {
    treatersTrucksAndTrailers: null;
}): Category {
    return "killTrucks" in value ? Category.killTrucks : "floatTrailer" in value ? Category.floatTrailer : "spareTractors" in value ? Category.spareTractors : "fracPumps" in value ? Category.fracPumps : "misc" in value ? Category.misc : "combo" in value ? Category.combo : "transports" in value ? Category.transports : "acidFracs" in value ? Category.acidFracs : "treatersTrucksAndTrailers" in value ? Category.treatersTrucksAndTrailers : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pump: null;
} | {
    pickup: null;
} | {
    tractor: null;
} | {
    trailer: null;
}): AssetType {
    return "pump" in value ? AssetType.pump : "pickup" in value ? AssetType.pickup : "tractor" in value ? AssetType.tractor : "trailer" in value ? AssetType.trailer : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: null;
} | {
    deleted: null;
} | {
    updated: null;
} | {
    paired: null;
} | {
    unpaired: null;
}): Variant_created_deleted_updated_paired_unpaired {
    return "created" in value ? Variant_created_deleted_updated_paired_unpaired.created : "deleted" in value ? Variant_created_deleted_updated_paired_unpaired.deleted : "updated" in value ? Variant_created_deleted_updated_paired_unpaired.updated : "paired" in value ? Variant_created_deleted_updated_paired_unpaired.paired : "unpaired" in value ? Variant_created_deleted_updated_paired_unpaired.unpaired : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DownAsset>): Array<DownAsset> {
    return value.map((x)=>from_candid_DownAsset_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DownAssetWithPairing>): Array<DownAssetWithPairing> {
    return value.map((x)=>from_candid_DownAssetWithPairing_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetPairing>): Array<AssetPairing> {
    return value.map((x)=>from_candid_AssetPairing_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetHistory>): Array<AssetHistory> {
    return value.map((x)=>from_candid_AssetHistory_n47(_uploadFile, _downloadFile, x));
}
function to_candid_AssetLabel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetLabel): _AssetLabel {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_AssetType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetLabel | null): [] | [_AssetLabel] {
    return value === null ? candid_none() : candid_some(to_candid_AssetLabel_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    pump: null;
} | {
    pickup: null;
} | {
    tractor: null;
} | {
    trailer: null;
} {
    return value == AssetType.pump ? {
        pump: null
    } : value == AssetType.pickup ? {
        pickup: null
    } : value == AssetType.tractor ? {
        tractor: null
    } : value == AssetType.trailer ? {
        trailer: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetLabel): {
    tundra: null;
} | {
    threeTank: null;
} | {
    f250: null;
} | {
    f350: null;
} | {
    twoTank: null;
} | {
    notApplicable: null;
} | {
    ptoTractor: null;
} | {
    dodgeRam: null;
} {
    return value == AssetLabel.tundra ? {
        tundra: null
    } : value == AssetLabel.threeTank ? {
        threeTank: null
    } : value == AssetLabel.f250 ? {
        f250: null
    } : value == AssetLabel.f350 ? {
        f350: null
    } : value == AssetLabel.twoTank ? {
        twoTank: null
    } : value == AssetLabel.notApplicable ? {
        notApplicable: null
    } : value == AssetLabel.ptoTractor ? {
        ptoTractor: null
    } : value == AssetLabel.dodgeRam ? {
        dodgeRam: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    killTrucks: null;
} | {
    floatTrailer: null;
} | {
    spareTractors: null;
} | {
    fracPumps: null;
} | {
    misc: null;
} | {
    combo: null;
} | {
    transports: null;
} | {
    acidFracs: null;
} | {
    treatersTrucksAndTrailers: null;
} {
    return value == Category.killTrucks ? {
        killTrucks: null
    } : value == Category.floatTrailer ? {
        floatTrailer: null
    } : value == Category.spareTractors ? {
        spareTractors: null
    } : value == Category.fracPumps ? {
        fracPumps: null
    } : value == Category.misc ? {
        misc: null
    } : value == Category.combo ? {
        combo: null
    } : value == Category.transports ? {
        transports: null
    } : value == Category.acidFracs ? {
        acidFracs: null
    } : value == Category.treatersTrucksAndTrailers ? {
        treatersTrucksAndTrailers: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upcoming_expired): {
    upcoming: null;
} | {
    expired: null;
} {
    return value == Variant_upcoming_expired.upcoming ? {
        upcoming: null
    } : value == Variant_upcoming_expired.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
